#!/usr/bin/env python3
"""PAM account hook. Applied only to the dedicated VPN Linux group."""

import os
import sys

from sshvpn_policy import admit_connection, managed_account


def main():
    if os.geteuid() != 0 or os.environ.get("PAM_TYPE") != "account":
        return 1
    username = os.environ.get("PAM_USER", "")
    try:
        if not managed_account(username):
            return 0
        return 0 if admit_connection(username, os.getppid()) else 1
    except (OSError, KeyError, ValueError):
        return 1


if __name__ == "__main__":
    sys.exit(main())
