#!/usr/bin/env python3
"""PAM account hook. Applied only to the dedicated VPN Linux group."""

import os
import subprocess
import sys

from sshvpn_policy import admit_connection, managed_account


def main():
    if os.geteuid() != 0 or os.environ.get("PAM_TYPE") != "account":
        return 1
    username = os.environ.get("PAM_USER", "")
    try:
        if not managed_account(username):
            return 0
        egress = subprocess.run(
            ["/usr/sbin/nft", "list", "table", "inet", "sshvpn_egress"],
            stdout=subprocess.DEVNULL, stderr=subprocess.DEVNULL, timeout=3,
        )
        if egress.returncode != 0:
            return 1
        return 0 if admit_connection(username, os.getppid(), remote_ip=os.environ.get("PAM_RHOST")) else 1
    except (OSError, KeyError, ValueError, RuntimeError, subprocess.TimeoutExpired):
        return 1


if __name__ == "__main__":
    sys.exit(main())
